FROM node:lts-alpine

ENV PUBLIC_ENABLE_DEV_POSTS=true
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn install --pure-lockfile --prefer-offline
COPY . .
EXPOSE 4567
CMD ["yarn", "run", "dev"]
